import Job from "@/interfaces/Job";

const jobs: Job[] = [
  {
    company: "Ten Tech EC",
    period: "2014 - 2018",
    picture: "/tentech.png",
    description:
      "Full stack developer, PLC developer and database administrator. Developing custom software for customers in Latin America. Managing, maintaining and creating reports for the company related to expenses and projections.",
    technologies: [
      "Ladder",
      "Arduino",
      "Assembly",
      "C++",
      "C#",
      "HTML",
      "CSS",
      "Javascript",
      "MATLAB",
      "WordPress",
      "React",
      "Python",
      "Pandas",
      "PySpark",
      "Data Science",
      "ETLs",
      "Data pipelines",
      "Git",
      "Github",
      "PostgreSQL",
    ],
  },
  {
    company: "ESPE",
    period: "2018",
    picture: "/espe.webp",
    description:
      "Leader software developer of a team focused on the rehabilitation of kids with autism (Social robots).",
    technologies: ["C++", "VBScript", "React", "Material UI"],
  },
  {
    company: "Localhost",
    period: "2019 - 2020",
    picture: "/localhost.jpg",
    description:
      "CEO and Developer. Creating an scalable platform with terraform and react to provide customers with websites built in wordpress and hosted by Localhost.",
    technologies: [
      "Jira",
      "Confluence",
      "Bitbucket",
      "SCRUM",
      "Kanban",
      "Leadership",
      "Figma",
      "Illustrator",
      "CI / CD",
      "Terraform",
      "Software Architecture",
    ],
  },
  {
    company: "Kings of Binary",
    period: "2019 - 2021",
    picture: "/kingsofbinary.jpg",
    description:
      "Backend Developer, specialist in Node.js and Python. Creating the infrastructure and the backend for an academy with multiple users.",
    technologies: [
      "Node.js",
      "Next.js",
      "Flask",
      "Firebase",
      "Linode",
      "Nginx",
      "Certbot",
      "Wordpress",
      "Terraform",
      "Azure",
      "MQL4 - MQL5",
      "Electron",
      "Blockchain",
      "Solidity",
      "Ganache",
      "Coinpayments",
      "Hotmart",
      "Stripe",
    ],
  },
  {
    company: "Devsu",
    period: "2020 - 2021",
    picture: "/devsu.jpeg",
    description:
      "Senior Developer, specialist in Python and Node.js, leadering the development of a project with big traffic and demand using real time services",
    technologies: [
      "AngularJS",
      "Angular",
      "Django",
      "Docker",
      "Celery",
      "CI/CD",
      "Jenkins",
      "Grafana",
      "Websockets",
      "RabbitMQ",
      "AWS",
      "Firebase",
      "Data Studio",
      "Twilio",
      "Wordpress",
      "Stripe",
      "Solidity",
      "Remix",
    ],
  },
  {
    company: "EveryMundo",
    period: "2021 - Current",
    picture: "/everymundo.jpeg",
    description:
      "Senior Backend Developer, specialist in Python and Node.js. Tech lead of an application that receives, transforms and delivers data to different services in a microservices network.",
    technologies: [
      "Microservices",
      "Distributed Systems",
      "Database Administrator",
      "Django",
      "MongoDB",
      "AngularJS",
      "Docker",
      "Celery",
      "CI/CD",
      "Jenkins",
      "AWS",
      "Google Business Profile",
    ],
  },
];

export default jobs;
