import Script from "next/script";

export default function Head() {
  return (
    <>
      <Script
        id="gtag-async-script"
        async
        src="https://www.googletagmanager.com/gtag/js?id=G-L5GLGTEGF4"
      ></Script>

      <Script
        id="gtag-sync-script"
        dangerouslySetInnerHTML={{
          __html: `window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-L5GLGTEGF4');`,
        }}
      ></Script>

      <title>Zpaceway</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />

      <meta
        name="theme-color"
        content="#5eead4"
        media="(prefers-color-scheme: light)"
      />
      <meta
        name="theme-color"
        content="#5eead4"
        media="(prefers-color-scheme: dark)"
      />

      <link rel="icon" href="/zpaceway.jpg" />
    </>
  );
}
