export default function Head() {
  return (
    <>
      <title>Zpaceway</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />

      <meta
        name="theme-color"
        content="#5eead4"
        media="(prefers-color-scheme: light)"
      />
      <meta
        name="theme-color"
        content="#5eead4"
        media="(prefers-color-scheme: dark)"
      />

      <link rel="icon" href="/zpaceway.jpg" />
    </>
  );
}
