import Script from "next/script";

export default function Head() {
  return (
    <>
      <Script
        id="gtag-header"
        dangerouslySetInnerHTML={{
          __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-NJZTHVT');`,
        }}
      ></Script>

      <title>Zpaceway</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />

      <meta
        name="theme-color"
        content="#5eead4"
        media="(prefers-color-scheme: light)"
      />
      <meta
        name="theme-color"
        content="#5eead4"
        media="(prefers-color-scheme: dark)"
      />

      <link rel="icon" href="/zpaceway.jpg" />
    </>
  );
}
